# Generated by Django 4.2.30 on 2026-05-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Oceanix', max_length=200)),
                ('tagline', models.CharField(default='Plantcare commerce for modern homes', max_length=500)),
                ('whatsapp_number', models.CharField(default='919999999999', max_length=20)),
                ('whatsapp_message', models.TextField(default='Hi Oceanix, I need help with my order.')),
                ('footer_text', models.TextField(default='Oceanix E-Commerce Private Limited. Built with Django, AI-guided product insights, and price comparison.')),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
