# Generated by Django 4.2.30 on 2026-05-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=50)),
                ('logger_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('pathname', models.CharField(blank=True, max_length=500, null=True)),
                ('func_name', models.CharField(blank=True, max_length=200, null=True)),
                ('line_no', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Log',
                'verbose_name_plural': 'Site Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
