# Generated by Django 4.2.30 on 2026-05-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sitelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Kitchen', 'Kitchen'), ('Bathroom', 'Bathroom'), ('Halls', 'Halls'), ('Rooms', 'Rooms'), ('Bedrooms', 'Bedrooms'), ('Occasions', 'Occasions'), ('Others', 'Others')], default='Others', max_length=50),
        ),
    ]
